"""Get posts of a specific user

Revision ID: 6929e803c203
Revises: e4a588bfa879
Create Date: 2022-01-28 11:39:49.441472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6929e803c203'
down_revision = 'e4a588bfa879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
