"""Change in tests

Revision ID: e105d7ff5b65
Revises: 6929e803c203
Create Date: 2022-01-28 11:46:54.109823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e105d7ff5b65'
down_revision = '6929e803c203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
